OPENAI_API_KEY = "openai-api-key"
VLLM_API_KEY = "vllm-api-key"

RUN_ENV = "local" 

LOCAL_API_BASE = "http://kong:8000/v1"
LOCAL_EMBEDDING_MODEL = "intfloat/multilingual-e5-large-instruct"
LOCAL_CHAT_MODEL = "google/gemma-3-1b-it"

OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"
OPENAI_CHAT_MODEL = "gpt-4o"

OPENROUTER_API_BASE = "https://openrouter.ai/api/v1"
OPENROUTER_EMBEDDING_MODEL = "text-embedding-3-large"
OPENROUTER_CHAT_MODEL = "google/gemma-3-27b-it:free"
